#!/bin/bash

# Get the current directory
directory_path="."

# Loop through all files in the directory
for file in "$directory_path"/*; do
  # Check if it's a file
  if [ -f "$file" ]; then
    chmod u+x "$file"
    echo "Permissions changed for $file"
  fi
done
